// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69bKGWAnLEyz3fbuZH1IGqUIrPIqkclo',
    appId: '1:606997886021:web:bc8d47bf55b31fefa75f2c',
    messagingSenderId: '606997886021',
    projectId: 'push-noti-aa56e',
    authDomain: 'push-noti-aa56e.firebaseapp.com',
    storageBucket: 'push-noti-aa56e.appspot.com',
    measurementId: 'G-3X8FPBVL9D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY4PgtDOPXv4MgfPrX5U7i8wKpUZ5U2gQ',
    appId: '1:606997886021:android:8dcd1543097afee2a75f2c',
    messagingSenderId: '606997886021',
    projectId: 'push-noti-aa56e',
    storageBucket: 'push-noti-aa56e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv1fH76lpzKrbhl3XkGteqmIITH4rchas',
    appId: '1:606997886021:ios:a27600745b8c0613a75f2c',
    messagingSenderId: '606997886021',
    projectId: 'push-noti-aa56e',
    storageBucket: 'push-noti-aa56e.appspot.com',
    iosBundleId: 'com.example.notifyFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBv1fH76lpzKrbhl3XkGteqmIITH4rchas',
    appId: '1:606997886021:ios:a27600745b8c0613a75f2c',
    messagingSenderId: '606997886021',
    projectId: 'push-noti-aa56e',
    storageBucket: 'push-noti-aa56e.appspot.com',
    iosBundleId: 'com.example.notifyFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69bKGWAnLEyz3fbuZH1IGqUIrPIqkclo',
    appId: '1:606997886021:web:aca3f8bf4f96a1c9a75f2c',
    messagingSenderId: '606997886021',
    projectId: 'push-noti-aa56e',
    authDomain: 'push-noti-aa56e.firebaseapp.com',
    storageBucket: 'push-noti-aa56e.appspot.com',
    measurementId: 'G-E1VKCTW93F',
  );
}
